---
version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/src/alpine"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/src/terraform"
    schedule:
      interval: "daily"
